name: Build and push to Dropbox
on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew bootRun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: montudor/action-zip@v1
        with:
            args: zip -qq -r mudletdocs.zip MudletDocs
      - name: Upload reader files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mudletdocs.zip
          asset_name: mudlet-docs.zip
          tag: release
          overwrite: true